apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: djam-template
  annotations:
    github.com/project-slug: 'spotify-portal-demo/djam-template'
spec:
  type: other
  lifecycle: production
  owner: admins
