apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: my-software-template-djamaile
  title: My Software Template
  description: Software Template Demo
spec:
  owner: sharks
  type: service

  # These are the steps which are rendered in form input when a user navigates to the software template
  parameters:
    - title: Add component metadata
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  # here are the steps that are executed in series in the scaffolder backend
  steps:
    # Downloads single file and places it in the workspace.
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        # ℹ️ This should to be changed to a location where you have content you want to add to your template ℹ️
        url: https://github.com/spotify-portal-demo/djam-template/tree/main
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
